import time
import uuid

from pathlib import Path
from typing import Dict

import numpy as np
import torch
import ray

import mujoco
from gymnasium.wrappers import TimeLimit
from stable_baselines3.common.monitor import Monitor

from src.environment.env import CustomEnv
from src.buffers.buffer import ReplayBuffer
from src.utils.data_preprocessor import flatten_state

class EnvRunner:
    """
    Manages the execution and lifecycle of episodes within an environment 
    using a specific policy.
    """
    def __init__(
        self, 
        name: str,
        is_train: bool,
        scene_path: str,
        policy_net: torch.nn.Module,
        horizon: int = 1,
        num_episodes: int = 1,
        max_steps: int = 25000,
        frame_skips: int = 50,
        timestep: float = 0.002,
        render_mode: str = "human",
        buffer: ReplayBuffer = ReplayBuffer(),
        data_dir: str = "data",
        logs_dir: str = "logs",
        logs_location = None,
        seed: int = 42,
        device = 'cpu'
    ):
        """
        Initialize the environment runner for the TDCR simulation.

        This runner manages the interaction between the neural network policy 
        and the MuJoCo physics engine, handling data collection and timing.

        Args:
            is_train (bool): If true, saves the environment output to a npz file upon episode end.
            scene_path (str): Path to the MuJoCo XML configuration file.
            policy (nn.Module): The neural network model used to determine actions.
            horizon (int): Number of future actions to be generated by policy.
            num_episodes (int): Total number of episodes to execute.
            max_steps (int): The maximum number of steps allowed per episode before 
                truncation. At 10 Hz, 1000 steps = 100 seconds of simulated time.
            frame_skips (int): The number of physics steps to perform per agent 
                action. A value of 50 results in a 10 Hz control cycle 
                (50 steps * 0.002s = 0.1s per action).
            timestep (float): The physics integration discretization (in seconds). 
                0.002s (500 Hz) provides stable dynamics for tendon interactions.
            render_mode (str): Mode for visualization (e.g., "human", "rgb_array").
            buffer (ReplayBuffer): Data structure to store experience 
                tuples (s, a, r, s', d) for training.
            data_dir (str): The directory where the environment outputs will be saved.
            seed (int): Random seed for environment and policy reproducibility.
        """
        assert horizon >= 1, f"Horizon must be at least 1, but got {horizon}"

        self.is_train = is_train
        self.scene_path = scene_path
        self.policy_net = policy_net
        self.horizon = horizon
        self.buffer = buffer
        self.num_episodes = num_episodes
        self.max_steps = max_steps
        self.data_dir = Path(data_dir)
        self.logs_dir = Path(logs_dir)
        self.seed = seed
        self.device = device

        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.logs_dir.mkdir(parents=True, exist_ok=True)

        self.env = CustomEnv(scene_path, render_mode, frame_skips, timestep)
        self.env = TimeLimit(self.env, max_episode_steps=self.max_steps)

        if logs_location is not None:
            # Create runs folder if it does not exist
            run_folder_path = self.logs_dir / Path(logs_location)
            run_folder_path.mkdir(parents=True, exist_ok=True)
            # Setup gynasium monitor
            self.monitor_file = run_folder_path / f"worker{name}_monitor"
            self.env = Monitor(self.env, filename=str(self.monitor_file))

    def _get_action(self, state: Dict) -> np.ndarray:
        r_state = flatten_state(state, self.device).view(1, 1, -1)

        plan, _ = self.policy_net.sample(r_state, self.horizon)
        plan = plan.detach().cpu().numpy().squeeze() # [Horizon, A_dim]

        # Receding horizon
        if plan.ndim > 1:
            action = plan[0]
        else:
            action = plan

        return action
    
    def _save_buffer(self):
        filename = f"{self.data_dir}/{str(uuid.uuid4())[:8]}_{time.strftime("%Y%m%d_%H%M")}"
        if self.is_train:
            self.buffer.save(filename)
            self.buffer.clear()
    
    def run_episodes(self):
        for episode in range(self.num_episodes):

            state, info = self.env.reset(seed=self.seed)
            done = False
            step_count = 0

            while not done:
                action = self._get_action(state)

                next_state, reward, terminated, truncated, info = self.env.step(action)
                
                done = terminated or truncated

                # Only add during training sessions
                # Skip add for step 1 because of state type mismatch
                if self.is_train and step_count >= 1:
                    self.buffer.add(state, action, reward, next_state, done)
                step_count += 1

                state = next_state
                self.env.render()

            self._save_buffer()

    def run_session(self):
        try:
            self.run_episodes()

        except (KeyboardInterrupt, mujoco.FatalError, Exception) as e:
        
            if isinstance(e, KeyboardInterrupt):
                print(f"\n\033[96m[INFO] Simulation stopped by user.\033[0m")

            elif isinstance(e, mujoco.FatalError):
                print(f"\n\033[1;31m[CRITICAL] MuJoCo Engine crashed! {e}\033[0m")

            else:
                print(f"\n\033[93m[ERROR] Unexpected error: {e}\033[0m")
                import traceback
                traceback.print_exc()

            self._save_buffer()

        finally:
            self.env.close()

@ray.remote
class ParallelEnvRunner(EnvRunner):
    def __init__(self, name, is_train, scene_path, policy_net, config, logs_location):
        super().__init__(
            name=name,
            is_train=is_train,
            scene_path=scene_path,
            policy_net=policy_net,
            horizon=config["agent"]["horizon"],
            num_episodes=config["env"]["num_episodes"],
            max_steps=config["env"]["max_steps"],
            frame_skips=config["env"]["frame_skips"],
            timestep=config["env"]["timestep"],
            render_mode=config["env"]["render"],
            seed=config["seed"],
            device=config["device"],
            logs_location=logs_location
        )

    def run_session_remote(self):
        return self.run_session()