scene: "tdcr_sim_mujoco/assets/tdcr/tdcr_linear_base_5_cyl_real.xml"
workspace_npz: "tdcr_sim_mujoco/data/workspace_train.npz"

epochs: 40
device: "cuda"
seed: 42

env:
  name: "tdcr-v1"
  render: "rgb_array"
  run_env: True
  num_episodes: 5
  max_steps: 300
  num_workers: 2
  frame_skips: 50
  timestep: 0.002
  allow_contact_goals: False
  rollout_data_dir: "tdcr_sim_mujoco/data/rollouts"

  use_lookup_reward: True
  lookup_search_radius: 1
  lookup_train_goal_count: 50
  lookup_npz_paths:
    - "/workspace/lookup_tables_5_cyl_RAO_LIKE_free.npz"
    - "/workspace/lookup_tables_5_cyl_RAO_LIKE_free_50-100.npz"
    - "/workspace/lookup_tables_5_cyl_RAO_LIKE_free_100-150.npz"
    - "/workspace/lookup_tables_5_cyl_RAO_LIKE_free_150-200.npz"

buffer:
  max_size: 1000000

agent:
  r_dim: 42
  action_dim: 2
  optimizer:
    _target_: "AdamW"
    betas: [0.9, 0.999]
    weight_decay: 0.01
  policy_lr: 0.0003
  q_lr: 0.001
  batch_size: 64
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  horizon: 1
  updates_per_epoch: 300   # fixed SAC gradient steps per epoch
  checkpoint: 300          # save checkpoint every N total updates

model:
  policy:
    d_embedding: 24
    d_hidden_enc: 48
    d_hidden_dec: 48
    d_state: 8
    d_latent: 16
    num_blocks_enc: 1
    num_blocks_dec: 3
    expand_dec: 2
    diffusion_steps: 20
    max_period: 250.0
    checkpoint: "None"
  q_network:
    d_embedding: 32
    d_hidden: 16
    d_state: 8
    num_blocks: 1
    checkpoint_q1: "None"
    checkpoint_q2: "None"